@host="http://localhost:5283"


GET http://localhost:5283/Dinner
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmMTIxNGRjNC05NmIxLTQ0OTctYmEyZi0wODRlYWFlNzI1Y2IiLCJnaXZlbl9uYW1lIjoic3RyaW5nIiwiZmFtaWx5X25hbWUiOiJzdHJpbmciLCJqdGkiOiIyZjhhNjAyZS1jMDZjLTQxZWYtOTY4YS05YzI0MTM2MmEyYzYiLCJleHAiOjE3MDgxNjQzNDAsImlzcyI6IkJ1YmJlckRpbm5lciIsImF1ZCI6IkJ1YmJlckRpbm5lciJ9.wWzvySMA22zd9yttLE-n0eR7Gp79Olu4HzQAT6ynRl8