@host="http://localhost:5283"


GET http://localhost:5283/Dinner
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkMmRjOGJiYS02NGYxLTQ0N2EtODgwYS04ZTBmNDBhZGM2MjYiLCJnaXZlbl9uYW1lIjoic3RyaW5nIiwiZmFtaWx5X25hbWUiOiJzdHJpbmciLCJqdGkiOiIxMzJjNzRlYS0zMGYxLTRmYTctYWQ3Ny00ZDQxYzE5NjFhMDgiLCJleHAiOjE3MDgxMTAwNTUsImlzcyI6IkJ1YmJlckRpbm5lciIsImF1ZCI6IkJ1YmJlckRpbm5lciJ9.6P0rsw2DJTDbEftSxL6KCSIEfqh1mEoXt3hLL9VDzRk