@host="http://localhost:5283"


GET http://localhost:5283/Dinner
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJCdWJlckRpbm5lci5Eb21haW4uTWVudS5WYWx1ZU9iamVjdHMuVXNlcklkIiwiZ2l2ZW5fbmFtZSI6InN0cmluZyIsImZhbWlseV9uYW1lIjoic3RyaW5nIiwianRpIjoiZWQyNTZjMmItNzFkNC00NzhiLTgyMzMtNzkxMzk0Yjc0MDhlIiwiZXhwIjoxNzA4NDI1OTczLCJpc3MiOiJCdWJiZXJEaW5uZXIiLCJhdWQiOiJCdWJiZXJEaW5uZXIifQ.ThtTtHnQNr7898mY2z0l6k5NT25VXKRBBCW8m-fIqUw


